-- Table: public.coal_seam
-- DROP TABLE IF EXISTS public.coal_seam;
CREATE TABLE IF NOT EXISTS PUBLIC.COAL_SEAM (
	SIGN_UUID UUID NOT NULL,
	SIGN_NAME TEXT COLLATE PG_CATALOG."default",
	LOCATION_X NUMERIC,
	LOCATION_Y NUMERIC,
	LOCATION_Z NUMERIC,
	DIRECTION_X NUMERIC,
	DIRECTION_Y NUMERIC,
	DIRECTION_Z NUMERIC,
	EFFICIENT BOOLEAN,
	GEO_TYPE TEXT COLLATE PG_CATALOG."default",
	BIG_CATEGORY TEXT COLLATE PG_CATALOG."default",
	MEDIUM_CATEGORY TEXT COLLATE PG_CATALOG."default",
	SMALL_CATEGORIES TEXT COLLATE PG_CATALOG."default",
	CREATION_TIME TIMESTAMP WITHOUT TIME ZONE,
	UPDATE_TIME TIMESTAMP WITHOUT TIME ZONE,
	ZOON GEOMETRY,
	CONSTRAINT COAL_SEAM_PKEY PRIMARY KEY (SIGN_UUID)
) TABLESPACE PG_DEFAULT;

ALTER TABLE IF EXISTS PUBLIC.COAL_SEAM OWNER TO POSTGRES;